name: SonarQube Integration
  sonarqube:
    name: SonarQube Integration
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@main
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}