name: "Scanning Files with SonarQube"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Scanning-With-SonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Scanning"
        with:
          fetch-depth: 0
        uses: sonarsource/sonarqube-scan-cl@main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: "Quality Gate"
        uses: sonarsource/sonarqube-quality-gate-action@main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}