name: "Scanning Files with SonarQube"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Scanning-With-SonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Scanning"
        with:
          fetch-depth: 0
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: "SonarQube-demo" # Replace 'your_project_key' with the actual key for your project
      - name: "Quality Gate"
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}